'use strict';
const $=s=>document.querySelector(s), params=new URLSearchParams(location.search), native=!!window.chrome?.webview;
const safeStore={get(){try{return JSON.parse(localStorage.getItem('massive95.settings')||'{}')}catch{return {}}},put(v){try{localStorage.setItem('massive95.settings',JSON.stringify(v));return true}catch{return false}}};
const stored=safeStore.get();if(stored.version!==2){stored.mode='recordings';stored.id='level-lattice';stored.cycle=true;stored.captions=false;}let mode=stored.mode==='generative'?'generative':'recordings',index=0,lastCycle=performance.now(),full=false,restoreFocus;
const engine=new MassiveSaver($('#art'));engine.speed=Number(stored.speed)||1;$('#speed').value=engine.speed;$('#speed-value').textContent=engine.speed+'×';$('#cycle').checked=!!stored.cycle;$('#captions').checked=stored.captions!==false;$('#interval').value=String(stored.interval||45);
function items(){return mode==='recordings'?RECORDINGS:SAVERS;}
function status(s){$('#status').textContent=s;}
function choose(i){let list=items();if(!list.length)return;index=(i+list.length)%list.length;let p=list[index];document.querySelectorAll('.preset').forEach((b,k)=>{b.classList.toggle('selected',index===k);b.setAttribute('aria-selected',String(index===k));b.tabIndex=index===k?0:-1;});$('#preset-title').textContent=p.name;$('#preset-description').textContent=p.note;$('#label-name').textContent=p.name.toUpperCase();$('#label-type').textContent=mode==='recordings'?'UNITY RECORDING · '+(p.captureDate||'ARCHIVE'):p.group;$('#screen-label').hidden=!$('#captions').checked;$('#count').textContent=`${String(index+1).padStart(2,'0')} / ${list.length}`;$('#display-source').textContent=mode==='recordings'?'ORIGINAL GAME VISUALS':'ARTISTIC INTERPRETATION';$('.display-top>span:last-child').textContent=mode==='recordings'?'ACTUAL GAME / UNITY':'INTERPRETATIONS / CANVAS';$('#play-error').hidden=true;$('#screen').classList.toggle('game-source',mode==='recordings');$('#art').hidden=mode==='recordings';$('#footage').hidden=mode!=='recordings';$('#speed').disabled=mode==='recordings';$('#speed-value').textContent=mode==='recordings'?'1×':engine.speed+'×';if(mode==='recordings'){$('#footage').poster=p.poster||'';$('#footage').src=p.src;$('#footage').playbackRate=1;if(!engine.paused)$('#footage').play().catch(()=>status('Press Play to start the recording'));}else{$('#footage').pause();$('#footage').removeAttribute('src');$('#footage').load();engine.select(p);}lastCycle=performance.now();status(p.name+(engine.paused?' · Paused':' · Running'));$('#pause').textContent=engine.paused?'Play':'Pause';}
function populate(id){$('#preset-list').replaceChildren();let last='',grid;items().forEach((p,i)=>{if(p.group!==last){let bank=document.createElement('details');bank.className='bank';bank.open=i===0;let h=document.createElement('summary');h.className='group-label';h.textContent=p.group.toUpperCase();grid=document.createElement('div');grid.className='bank-grid';bank.append(h,grid);$('#preset-list').append(bank);last=p.group;}let b=document.createElement('button');b.className='preset';b.role='option';b.dataset.index=i;let icon=document.createElement('span');icon.className='glyph';icon.style.color=p.color||'#d0e1b1';icon.textContent=p.glyph||'▤';if(p.poster){let thumb=document.createElement('img');thumb.src=p.poster;thumb.alt='';thumb.className='game-thumb';thumb.loading='lazy';b.append(thumb);}else b.append(icon);let name=document.createElement('span');name.className='preset-name';name.textContent=p.name;b.append(name);b.title=p.name;b.onclick=()=>choose(i);b.ondblclick=()=>preview();grid.append(b);});$('#generative').setAttribute('aria-selected',String(mode==='generative'));$('#recordings').setAttribute('aria-selected',String(mode==='recordings'));$('#list-footer').textContent=mode==='recordings'?'18 UNITY RECORDINGS / 8 WORLDS':'8 WORLDS / 12 EVENT STUDIES';$('#source-note').textContent=mode==='recordings'?'Actual MASSIVE scenes, shaders and effects, recorded in Unity.':'Optional interpretations. These do not use the game’s renderers.';choose(Math.max(0,items().findIndex(x=>x.id===id)));}
function switchMode(next){mode=next;populate();}
$('#generative').onclick=()=>switchMode('generative');$('#recordings').onclick=()=>switchMode('recordings');
$('#preset-list').onkeydown=e=>{if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();choose(e.key==='Home'?0:e.key==='End'?items().length-1:index+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1));$('.preset.selected').closest('details').open=true;$('.preset.selected').focus();}};
$('.tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();switchMode(mode==='generative'?'recordings':'generative');$('#'+mode).focus();}};
$('#speed').oninput=e=>{engine.speed=+e.target.value;$('#speed-value').textContent=engine.speed+'×';};$('#captions').onchange=()=>$('#screen-label').hidden=!$('#captions').checked;$('#cycle').onchange=()=>lastCycle=performance.now();$('#interval').onchange=()=>lastCycle=performance.now();$('#pause').onclick=()=>{engine.paused=!engine.paused;$('#pause').textContent=engine.paused?'Play':'Pause';if(mode==='recordings'){if(engine.paused)$('#footage').pause();else $('#footage').play().catch(()=>status('Playback unavailable'));}status(items()[index].name+(engine.paused?' · Paused':' · Running'));};$('#previous').onclick=()=>choose(index-1);$('#next').onclick=()=>choose(index+1);$('#restart').onclick=()=>choose(index);$('#footage').onerror=()=>{$('#play-error').hidden=false;status('Recording unavailable');};
setInterval(()=>{if(!document.hidden&&!engine.paused&&$('#cycle').checked&&performance.now()-lastCycle>+$('#interval').value*1000)choose(index+1);},500);
async function preview(){restoreFocus=document.activeElement;full=true;$('#screen').classList.add('expanded');$('#exit-preview').hidden=false;try{await $('#screen').requestFullscreen();}catch{}engine.resize();$('#exit-preview').focus({preventScroll:true});}
function exit(){full=false;$('#screen').classList.remove('expanded');$('#exit-preview').hidden=true;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});engine.resize();restoreFocus?.focus({preventScroll:true});}
$('#preview').onclick=preview;$('#exit-preview').onclick=exit;document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&full)exit();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&full)exit();});
function settings(){return {version:2,mode,id:items()[index]?.id,speed:engine.speed,cycle:$('#cycle').checked,interval:+$('#interval').value,captions:$('#captions').checked};}
$('#apply').onclick=()=>{if(safeStore.put(settings())){status('Settings saved on this device.');$('#service').close();}else status('Settings could not be saved in this browser.');};
function info(title,html){$('#info-title').textContent=title;$('#info-body').innerHTML=html;$('#info').showModal();}function about(){info('About the cabinet','<h2>MASSIVE / Attract Cabinet</h2><p><b>Actual game</b> plays MASSIVE’s own Unity scenes, shaders, particle systems and effects. There are fresh captures of all eight levels plus ten archived gameplay and effect studies.</p><p>The videos repeat with a cut. Event footage is partial: the recordings do not individually document every level event.</p><p><b>Interpretations</b> is an optional collection of twenty hand-coded studies. Those studies do not use the game’s renderers.</p><p>Each recording identifies its scene, source revision and recording method in the <a href="sources.json" target="_blank" rel="noopener">capture manifest</a>.</p><p>Select a scene and press START for a full-screen view. AUTO ADVANCE cycles the collection. Service contains playback options and saves your choices on this device. Press Esc to return to the cabinet.</p><p>Windows 10/11 x64. The cabinet interface is built for modern browsers and Windows 10/11; it does not run on Windows 95.</p>');}
$('#info-close').onclick=$('#info-ok').onclick=()=>$('#info').close();$('#about-icon').onclick=about;$('#service-open').onclick=()=>$('#service').showModal();$('#service-close').onclick=()=>$('#service').close();
$('#download').onclick=()=>info('Install the Windows screen saver','<h2>Your own idle universe.</h2><p>Download and extract the Windows package, then run <b>Install.cmd</b>. The installer copies it to your user folder and opens Windows Screen Saver Settings.</p><p>Choose <b>Settings</b> to open the cabinet. Its <b>Service</b> panel contains playback options. Windows uses your existing idle timeout and sign-in preferences.</p><p>Requires Windows 10/11 x64 and Microsoft Edge WebView2 Runtime. This independent package is unsigned.</p><p><a href="https://github.com/jalulia/massive/releases/download/screensavers-v4/MASSIVE-95-Windows-x64.zip">Download Windows package ↓</a><br><a href="https://developer.microsoft.com/en-us/microsoft-edge/webview2/">Get WebView2 Runtime ↗</a></p>');
function clock(){ $('#clock').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}clock();setInterval(clock,30000);
populate(params.get('preset')||stored.id);if(params.has('run')||params.has('nativepreview')){document.body.classList.add('native-run');engine.paused=false;$('#pause').textContent='Pause';if(mode==='recordings')$('#footage').play().catch(()=>{});engine.resize();}
if(native&&params.has('run')){let born=performance.now(),initial=null;document.addEventListener('pointermove',e=>{if(performance.now()-born<1500){initial=[e.screenX,e.screenY];return;}if(initial&&Math.hypot(e.screenX-initial[0],e.screenY-initial[1])>8)window.chrome.webview.postMessage('exit');initial??=[e.screenX,e.screenY];});for(let ev of ['keydown','pointerdown'])document.addEventListener(ev,()=>window.chrome.webview.postMessage('exit'));}
document.addEventListener('visibilitychange',()=>{if(document.hidden)$('#footage').pause();else {lastCycle=performance.now();if(mode==='recordings'&&!engine.paused)$('#footage').play().catch(()=>{});}});
window.saverApp={engine,choose,switchMode,getState:()=>({mode,index,preset:items()[index]?.id,full,settings:settings()})};
